package com.tqs.tests;
// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.beans.Transient;
import java.util.*;

import org.junit.jupiter.api.extension.ExtendWith;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import io.github.bonigarcia.wdm.WebDriverManager;

import com.tqs.pages.HomePage;
import com.tqs.pages.LoginPage;
import com.tqs.pages.Dashboard;

import java.time.Duration;

public class Test1Test {

    WebDriver driver;


    @BeforeEach
    public void setUp() {
      driver = new FirefoxDriver();
      driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
    
    @AfterEach
    public void quitDriver() {
      driver.quit();
    }

    @Test
    public void tests(){
      driver.get("https://wwww.demoqa.com/login");

    HomePage homepage = new HomePage(driver);
    LoginPage loginpage = new LoginPage(driver);
    Dashboard dashboard = new Dashboard(driver);

    homepage.clickLoginButton();

    loginpage.setUsername("joaopinheiro");
    loginpage.setPassword("Joaopinheiro123!");

    loginpage.clickLoginButton();

    System.out.println("The page heading is - " + dashboard.getHeading());

    dashboard.clickLogoutButton();
    }

    

}
